---
title: "Comparison between the new method and the old method"
output: pdf_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/R/ihw_convex.R")
```

## Load Dataset

```{r}
##this file tests the proteomics example
library("IHWpaper")
library("IHW")
library(tidyverse)

proteomics_file <- system.file("extdata/real_data",
                               "science_signaling.csv", package = "IHWpaper")

proteomics_df <- read.csv(proteomics_file, stringsAsFactors = F)

proteomics_df$pvalue <- rank(proteomics_df$p1, ties.method="first")*proteomics_df$p1/nrow(proteomics_df) 
```

## Run the three methods

```{r}
num_bins <- seq(from = 10, to = 50, by = 10)
N <- length(num_bins)
```

```{r}
time.new <- rep(NA, N)
time.old <- rep(NA, N)
time.cvxr <- rep(NA, N)

rej_new <- rep(NA, N)
rej_old <- rep(NA, N)
rej_cvxr <- rep(NA, N)

for(i in 1:N){
  time.new[i] <- system.time(ihw_res_new <- ihw(proteomics_df$pvalue, proteomics_df$X..peptides, alpha = 0.1, nbins= num_bins[i], nfolds=5L, lambdas=seq(0,3,length=20), admm = F, new_method = T))[1]
  rej_new[i] <- IHW:::rejections(ihw_res_new)
  
  
  time.old[i] <- system.time(ihw_res_old <- IHWold:::ihwOld(proteomics_df$pvalue, proteomics_df$X..peptides, alpha = 0.1, nbins = num_bins[i], nfolds=5L, lambdas=seq(0,3,length=20)))[1]
  rej_old[i] <- IHW:::rejections(ihw_res_old)
  
  print(paste0("Ending iteration ", i))

}
```

## Plot the results
```{r}
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/proteomics_ihw_res_admm.RData")
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/proteomics_rej_admm.RData")
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/proteomics_time_admm.RData")

data <- data.frame(num_bins = num_bins, rejection_new = rej_new[1:5], rejection_admm = rej_admm[1:5], rejection_old = rej_old[1:5], time_admm = time.admm[1:5], time_new = time.new[1:5], time_old = time.old[1:5])
```

```{r}
#we first plot runtime versus bins
# Create the line plot
p1 <- ggplot(data) +
  geom_line(aes(x = num_bins, y = log(time_admm), col = "ADMM Method", linetype = "ADMM Method")) +
  geom_line(aes(x = num_bins, y = log(time_old), col = "Old IHW", linetype = "Old IHW")) +
  geom_line(aes(x = num_bins, y = log(time_new), col = "New Method", linetype = "New Method")) +
  labs(x = "Number of Bins", y = "Runtime (log sec)") +
scale_color_manual(values = c("ADMM Method" = "blue", "Old IHW" = "red", "New Method" = "green"), name = "Methods") +
  scale_linetype_manual(values = c("ADMM Method" = "solid", "Old IHW" = "solid", "New Method" = "solid"), name = "Methods")
```

```{r}
#we then plot rejections versus bins
# Create the line plot
p2 <- ggplot(data) +
  geom_line(aes(x = num_bins, y = rejection_admm, col = "ADMM Method", linetype = "ADMM Method")) +
  geom_line(aes(x = num_bins, y = rejection_old, col = "Old IHW",  linetype = "Old IHW")) +
  geom_line(aes(x = num_bins, y = rejection_new, col = "New Method", linetype = "New Method")) +
  labs(x = "Number of Bins", y = "Number of Rejections") +
scale_color_manual(values = c("ADMM Method" = "blue", "Old IHW" = "red", "New Method" = "green"), name = "Methods") +
  scale_linetype_manual(values = c("ADMM Method" = "solid", "Old IHW" = "solid", "New Method" = "dashed"), name = "Methods")
```

```{r}
p1
```

```{r}
p2
```
```{r}
#plot weights: num bins = 50
IHW:::plot(ihw_res_admm)
IHW:::plot(ihw_res_old)
IHW:::plot(ihw_res_new)
```

## 2nd example
```{r}
library("IHWpaper")
library("IHW")
bottomly <- analyze_dataset("bottomly")
```

```{r}
num_bins <- seq(from = 10, to = 50, by = 10)
N <- length(num_bins)
```

## Run the three methods
```{r}
time.new <- rep(NA, N)
time.old <- rep(NA, N)
#time.cvxr <- rep(NA, N)

rej_new <- rep(NA, N)
rej_old <- rep(NA, N)
#rej_cvxr <- rep(NA, N)
```

```{r}
for(i in 1:N){
  time.new[i] <- system.time(ihw_res_new <- ihw(bottomly$pvalue, bottomly$baseMean, 0.1, nbins = num_bins[i], nfolds_internal=4L, nfolds=5L, admm = F, new_method = T))[1]
  rej_new[i] <- IHW:::rejections(ihw_res_new)
  
  
  time.old[i] <- system.time(ihw_res_old <- IHWold:::ihwOld(bottomly$pvalue, bottomly$baseMean, 0.1, nbins = num_bins[i], nfolds_internal=4L, nsplits_internal=5L))[1]
  rej_old[i] <- IHW:::rejections(ihw_res_old)

  #time.cvxr[i] <- system.time(ihw_res_cvxr <- IHW:::ihw(bottomly$pvalue, bottomly$baseMean, 0.1, nbins = num_bins[i], nfolds_internal=4L, nfolds=5L, admm = F))[1]
  #rej_cvxr[i] <- IHW:::rejections(ihw_res_cvxr)
  
  print(paste0("Ending iteration ", i))

}
```

```{r}
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/RNAseq_ihw_res_admm.RData")
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/RNAseq_time_admm.RData")
load("~/Library/Mobile Documents/com~apple~CloudDocs/Desktop/UchicagoStudy/Nikolaos Research/IHW_New/CVXR_comparison/RNAseq_rej_admm.RData")

data <- data.frame(num_bins = num_bins, rejection_new = rej_new[1:5], rejection_admm = rej_admm[1:5], rejection_old = rej_old[1:5], time_admm = time.admm[1:5], time_new = time.new[1:5], time_old = time.old[1:5])
```

```{r}
library(tidyverse)
#we first plot runtime versus bins
# Create the line plot
p1 <- ggplot(data) +
  geom_line(aes(x = num_bins, y = time_admm, col = "ADMM Method", linetype = "ADMM Method")) +
  geom_line(aes(x = num_bins, y = time_old, col = "Old IHW", linetype = "Old IHW")) +
  geom_line(aes(x = num_bins, y = time_new, col = "New Method", linetype = "New Method")) +
  labs(x = "Number of Bins", y = "Runtime (log sec)") +
scale_color_manual(values = c("ADMM Method" = "blue", "Old IHW" = "red", "New Method" = "green"), name = "Methods") +
  scale_linetype_manual(values = c("ADMM Method" = "solid", "Old IHW" = "solid", "New Method" = "solid"), name = "Methods")
```

```{r}
#we then plot rejections versus bins
# Create the line plot
p2 <- ggplot(data) +
  geom_line(aes(x = num_bins, y = rejection_admm, col = "ADMM Method", linetype = "ADMM Method")) +
  geom_line(aes(x = num_bins, y = rejection_old, col = "Old IHW",  linetype = "Old IHW")) +
  geom_line(aes(x = num_bins, y = rejection_new, col = "New Method", linetype = "New Method")) +
  labs(x = "Number of Bins", y = "Number of Rejections") +
scale_color_manual(values = c("ADMM Method" = "blue", "Old IHW" = "red", "New Method" = "green"), name = "Methods") +
  scale_linetype_manual(values = c("ADMM Method" = "solid", "Old IHW" = "solid", "New Method" = "dashed"), name = "Methods")
```

```{r}
p1
```

```{r}
p2
```

```{r}
#plot weights: num bins = 50
IHW:::plot(ihw_res_admm)
IHW:::plot(ihw_res_old)
IHW:::plot(ihw_res_new)
```
