---
title: "Plots of Intuition"
output: html_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intuition continuous case
```{r}
library(ggplot2)
library(cowplot)
library(gridExtra)

# Create a sequence of x values
x <- seq(0, 10, length.out = 100)

# Define the functions
f1 <- 0.5 *sqrt(x) / (0.5 *sqrt(x) + (1-0.5)/2)
f2 <- 0.3 *sqrt(x) / (0.3 *sqrt(x) + (1-0.3)/2)
f3 <- 0.2 *sqrt(x) / (0.2 *sqrt(x) + (1-0.2)/2)

# Determine the maximum value among all functions
max_value <- max(max(f1), max(f2), max(f3))

# Create the data frame for plotting
df <- data.frame(x = x, f1 = f1, f2 = f2, f3 = f3)

# Create plots
p1 <- ggplot(df, aes(x = x, y = f1)) +
  geom_line(color = "blue") +
  geom_hline(yintercept = 0.4 * max_value, linetype = "dashed", color = "red") +
  geom_point(data = subset(df, f1 == 0), aes(y = f1), color = "red", size = 1) +
  geom_vline(xintercept = 0.1, linetype = "dashed", color = "black") +
  annotate("text", x = 8, y = 0.25 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 0.6, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  labs(x = " ", y = "Local FDR") +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_x_continuous(breaks = seq(0, 10, by = 2)) +  # Add specific x-axis numbers
  ylim(0, max_value)  # Set the same y-axis limit for all plots

p2 <- ggplot(df, aes(x = x, y = f2)) +
  geom_line(color = "blue") +
  geom_hline(yintercept = 0.4 * max_value, linetype = "dashed", color = "red") +
  geom_point(data = subset(df, f2 == 0), aes(y = f2), color = "red", size = 1) +
  geom_vline(xintercept = 0.4, linetype = "dashed", color = "black") +
  annotate("text", x = 8, y = 0.25 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 0.9, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  labs(x = "Rejection Threhold t", y = " ") +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_x_continuous(breaks = seq(0, 10, by = 2)) +  # Add specific x-axis numbers
  ylim(0, max_value)  # Set the same y-axis limit for all plots

p3 <- ggplot(df, aes(x = x, y = f3)) +
  geom_line(color = "blue") +
  geom_hline(yintercept = 0.4 * max_value, linetype = "dashed", color = "red") +
  geom_point(data = subset(df, f3 == 0), aes(y = f3), color = "red", size = 1) +
  geom_vline(xintercept = 1.1, linetype = "dashed", color = "black") +
  annotate("text", x = 8, y = 0.25 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 1.6, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  labs(x = " ", y = " ") +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_x_continuous(breaks = seq(0, 10, by = 2)) +  # Add specific x-axis numbers
  ylim(0, max_value) # Set the same y-axis limit for all plots


```

```{r}
library(ggpubr)
# Display the plots
ggarrange(p1, p2, p3, nrow = 1, label.x = "rejection threshold")

```


## Piecewise linear case
```{r}
library(ggplot2)
library(cowplot)

# Create a sequence of x values
x <- seq(0.001, 3, length.out = 100)

# Define the piecewise constant function f(x)
f1 <- ifelse(x <= 0, 0, 
             ifelse(x <= 1, 0.5, 
                    ifelse(x <= 2, 1.5, 
                           4)))

segments_df <- data.frame(
  xstart = head(x, -1),
  xend = tail(x, -1),
  y = f1[-length(f1)]
)

# Plot the piecewise constant function with horizontal segments
p4 <- ggplot(segments_df, aes(x = xstart, xend = xend, y = y, yend = y)) +
  geom_segment(size = 1, color = "blue") +
  geom_hline(yintercept = 2.5, linetype = "dashed", color = "red") +
  geom_point(aes(x =2, y = 2.5), color = "red", size = 1) +
  geom_vline(xintercept = 2, linetype = "dashed", color = "black") +
  labs(x = " ", y = " ") +
  annotate("text", x = 2.7, y = 0.7 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 2.2, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_y_continuous(breaks = NULL, limits = c(0, max_value)) +
  scale_x_continuous(breaks = NULL) +
  ylim(0, max_value) +
  xlim(0, 3)
```
```{r}
f2 <- ifelse(x <= 2, 2.8, 
                           3.5)

segments_df <- data.frame(
  xstart = head(x, -1),
  xend = tail(x, -1),
  y = f2[-length(f2)]
)

# Plot the piecewise constant function with horizontal segments
p5 <- ggplot(segments_df, aes(x = xstart, xend = xend, y = y, yend = y)) +
  geom_segment(size = 1, color = "blue") +
  geom_hline(yintercept = 2.5, linetype = "dashed", color = "red") +
  geom_point(aes(x =0, y = 2.5), color = "red", size = 1) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
  labs(x = " ", y = "Local FDR") +
  annotate("text", x = 2.7, y = 0.7 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 0.2, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_y_continuous(breaks = NULL, limits = c(0, max_value)) +
  scale_x_continuous(breaks = NULL) +
  ylim(0, max_value) +
  xlim(0, 3)
```
```{r}
f3 <- ifelse(x <= 0, 0, 
             ifelse(x <= 1, 0.3, 
                    ifelse(x <= 2, 2.5, 
                           3.5)))

segments_df <- data.frame(
  xstart = head(x, -1),
  xend = tail(x, -1),
  y = f3[-length(f3)]
)

# Plot the piecewise constant function with horizontal segments
p6 <- ggplot(segments_df, aes(x = xstart, xend = xend, y = y, yend = y)) +
  geom_segment(size = 1, color = "blue") +
  geom_hline(yintercept = 2.5, linetype = "dashed", color = "red") +
  geom_point(aes(x =1.5, y = 2.5), color = "red", size = 1) +
  geom_vline(xintercept = 1.5, linetype = "dashed", color = "black") +
  geom_vline(xintercept = 1, linetype = "dashed", color = "purple") +
  geom_vline(xintercept = 2, linetype = "dashed", color = "purple") +
  labs(x = "Rejection Threshold t", y = " ") +
  annotate("text", x = 2.7, y = 0.7 * max_value, label = expression(lambda), color = "red")+
  annotate("text", x = 1.7, y = 0, label = expression(paste("t"[g]^"*")), color = "black", vjust = 0.1) +
  annotate("text", x = 1.2, y = 0, label = expression(paste("l"[g]^"*")), color = "purple", vjust = 0.1) +
  annotate("text", x = 2.2, y = 0, label = expression(paste("u"[g]^"*")), color = "purple", vjust = 0.1) +
  theme(axis.text = element_blank(), aspect.ratio = 0.7) +
  scale_y_continuous(breaks = NULL, limits = c(0, max_value)) +
  scale_x_continuous(breaks = NULL) +
  ylim(0, max_value) +
  xlim(0, 3)
```

```{r}
library(ggpubr)
ggarrange(p5, p6, p4, nrow = 1)
```