---
title: "Runtime_visualization"
output: pdf_document
date: "2025-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Changing the number of observations
```{r}
#load the data
#load the data (might need to change the file path, please run the Simulation_nrows_runtime_comparison.R first!)
load("~/Desktop/Columbia Stats PhD/Optimization (Nikos)/Optimization_New/Tasks_9_9/nrows_final_results_computational_time_microbench_300.RData")
```

```{r}
library(dplyr)
library(ggplot2)

# If your column is named `nrows`, rename for convenience
df <- final_results

# Make sure method is a factor (optional: order the legend)
df <- df %>%
  mutate(method = factor(method, levels = c("IHW Binning","IHW OLD")))

plt_runtime <- ggplot(df, aes(x = nrows, y = runtime_median_sec,
               color = method, group = method)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(labels = scales::label_number()) +
  labs(x = "Number of rows (n)",
       y = "Runtime (sec, median)",
       color = "Method",
       title = "Runtime vs. nrows") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right")

plt_runtime
```

```{r}
plt_power <- ggplot(df, aes(x = nrows, y = power,
               color = method, group = method)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(labels = scales::label_number()) +
  labs(x = "Number of rows (n)",
       y = "power",
       color = "Method",
       title = "power vs. nrows") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right")

plt_power

```

## Changing the number of nbins
```{r}
#load the data (might need to change the file path, please run the Simulation_nbins_runtime_comparison.R first!)
load("~/Desktop/Columbia Stats PhD/Optimization (Nikos)/Optimization_New/Tasks_9_9/nbins_final_results_computational_time_microbench.RData")
```

```{r}
library(dplyr)
library(ggplot2)

# If your column is named `nrows`, rename for convenience
df <- final_results

# Make sure method is a factor (optional: order the legend)
df <- df %>%
  mutate(method = factor(method, levels = c("IHW Binning","IHW OLD")))

plt_runtime <- ggplot(df, aes(x = nbins, y = runtime_median_sec,
               color = method, group = method)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(labels = scales::label_number()) +
  labs(x = "Number of bins (n)",
       y = "Runtime (sec)",
       color = "Method",
       title = "Runtime vs. nbins") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right")

plt_runtime
```

```{r}
plt_power <- ggplot(df, aes(x = nbins, y = power,
               color = method, group = method)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_x_continuous(labels = scales::label_number()) +
  labs(x = "Number of bins (n)",
       y = "power",
       color = "Method",
       title = "power vs. nbins") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right")

plt_power

```